import React,{useEffect,useState} from 'react';
import { Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { Product,sellerApi } from '../api';
import { colors,radius } from '../theme';

export function AIRecommendationScreen(){
  const[products,setProducts]=useState<Product[]>([]);const[selected,setSelected]=useState<number|null>(null);const[price,setPrice]=useState<{currentPrice:number;discountPct:number;minutesLeft:number}|null>(null);const[strategy,setStrategy]=useState('');const[message,setMessage]=useState('');
  useEffect(()=>{sellerApi.products().then(page=>{setProducts(page.content);if(page.content[0])setSelected(page.content[0].id)}).catch(()=>undefined)},[]);
  useEffect(()=>{if(!selected)return;Promise.all([sellerApi.price(selected),sellerApi.strategy(selected)]).then(([next,plan])=>{setPrice(next);setStrategy(plan.message)}).catch(()=>{setPrice(null);setStrategy('AI 추천 서버 응답을 기다리고 있습니다.')})},[selected]);
  const apply=async()=>{if(!selected||!price)return;await sellerApi.applyPrice(selected,{price:price.currentPrice});setMessage('추천 가격을 상품에 적용했습니다.')};
  return <ScrollView contentContainerStyle={s.root}><Text style={s.title}>AI 추천가</Text><Text style={s.body}>등록 상품별 실시간 추천 가격과 판매 전략을 확인하세요.</Text>{products.map(product=><Pressable key={product.id} onPress={()=>setSelected(product.id)} style={[s.product,selected===product.id&&s.selected]}><Text style={s.productName}>{product.name}</Text><Text>{product.currentPrice.toLocaleString()}원</Text></Pressable>)}{selected?<View style={s.card}><Text style={s.label}>현재 AI 추천가</Text><Text style={s.price}>{price?`${price.currentPrice.toLocaleString()}원`:'추천가 계산 중'}</Text>{price?<Text style={s.discount}>{price.discountPct}% 할인 · 마감 {price.minutesLeft}분 전</Text>:null}<Text style={s.strategy}>{strategy}</Text><Pressable disabled={!price} onPress={apply} style={[s.button,!price&&s.disabled]}><Text style={s.buttonText}>추천가 적용</Text></Pressable>{message?<Text style={s.message}>{message}</Text>:null}</View>:<Text style={s.empty}>등록 상품이 없습니다.</Text>}</ScrollView>;
}
const s=StyleSheet.create({root:{padding:16,paddingBottom:100},title:{fontSize:22,fontWeight:'700'},body:{fontSize:13,color:colors.g500,marginTop:6,marginBottom:18},product:{height:52,paddingHorizontal:14,borderWidth:1,borderColor:colors.g200,borderRadius:radius.sm,marginBottom:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selected:{borderColor:colors.primary500,backgroundColor:colors.primary100},productName:{fontSize:15,fontWeight:'600'},card:{marginTop:14,padding:18,borderRadius:radius.lg,backgroundColor:colors.g100},label:{fontSize:14,color:colors.g600},price:{fontSize:30,fontWeight:'700',color:colors.primary500,marginTop:6},discount:{fontSize:13,color:colors.info,marginTop:4},strategy:{fontSize:14,lineHeight:21,marginVertical:18},button:{height:54,borderRadius:radius.md,backgroundColor:colors.primary500,alignItems:'center',justifyContent:'center'},disabled:{backgroundColor:colors.g200},buttonText:{fontSize:16,fontWeight:'600',color:colors.white},message:{fontSize:12,color:colors.success,textAlign:'center',marginTop:10},empty:{textAlign:'center',color:colors.g500,marginTop:80}});
