import React,{useState} from 'react';
import { Alert,Modal,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { AppHeader,BottomNavigation,Product,ProductCard,ReservationStatus } from '../components/home';
import { Chip } from '../components/ui'; import { colors,radius } from '../theme'; import ChevronDownIcon from '../../icon/chevron_down.svg'; import { ReservationScreen } from './ReservationScreen'; import { MyPageScreen } from './MyPageScreen'; import { SellerHomeScreen } from './SellerHomeScreen';

const products:Product[]=[{id:1,title:'제주 흑돼지 모둠 도시락 세트',discount:'62.5%',shop:'춘자네 흑돼지 협재점',location:'제주시 한림읍 · 850m',detail:'당일 재고 · 마감 22:00',urgent:true,insight:'저녁 기온이 선선해 야외 야식 수요가 급증하고 있어요. 최소 판매가 직전까지 떨어뜨린 역대급 세일 기회를 놓치지 마세요!',original:'20,000원',price:'7,500원',remaining:'잔여수량 2개'},{id:2,title:'바다 전망 커플룸 당일 숙박권',discount:'20%',shop:'푸른바다 게스트하우스',location:'제주시 애월읍 · 2.4km',detail:'당일 공실 · 마감 23:00',insight:'애월 해안도로 주변에 야간 소나기 예보가 있습니다. 아늑한 바다뷰 객실을 싼값에 잡을 수 있는 찬스입니다!',original:'90,000원',price:'72,000원',remaining:'잔여수량 1개'}];
const categories=['전체','음식점','숙박','체험','렌탈 / 모빌리티','당일 재고','당일 공실','빈 시간대 자원'];

export function BuyerHomeScreen({onLogout,onWithdraw}:{onLogout:()=>Promise<void>;onWithdraw:()=>Promise<void>}){const[category,setCategory]=useState('전체');const[liked,setLiked]=useState<number[]>([]);const[purchase,setPurchase]=useState<Product|null>(null);const[reserve,setReserve]=useState<Product|null>(null);const[status,setStatus]=useState<ReservationStatus|undefined>();const[tab,setTab]=useState<'home'|'mypage'>('home');const[sellerMode,setSellerMode]=useState(false);const toggleLike=(id:number)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  if(sellerMode)return <SellerHomeScreen onBuyerMode={()=>setSellerMode(false)}/>;
  if(tab==='mypage')return <MyPageScreen onHome={()=>setTab('home')} onSellerMode={()=>setSellerMode(true)} onLogout={onLogout} onWithdraw={onWithdraw}/>;
  if(reserve)return <ReservationScreen product={reserve} onClose={()=>setReserve(null)} onComplete={()=>{setStatus('waiting');setLiked(v=>v.includes(reserve.id)?v:[...v,reserve.id]);setReserve(null)}}/>;
  return <View style={s.root}><AppHeader/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text style={s.heading}>로컬타임이 찾은 오늘 마감 특가 상품</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map(x=><Chip key={x} selected={category===x} onPress={()=>setCategory(x)}>{x}</Chip>)}</ScrollView><View style={s.sort}><Text style={s.sortText}>AI 추천순</Text><ChevronDownIcon width={24} height={24} color={colors.g500}/></View>{products.map(p=><ProductCard key={p.id} product={p} liked={liked.includes(p.id)} onLike={()=>toggleLike(p.id)} onBuy={()=>setPurchase(p)} onReserve={()=>setReserve(p)} status={p.id===1?status:undefined} onCancel={()=>setStatus(undefined)} onDelete={()=>setStatus(undefined)} onReason={()=>Alert.alert('거절 사유','판매 가능한 수량이 부족하여 예약이 거절되었습니다.')}/>)}</ScrollView><BottomNavigation active="home" onSelect={setTab}/><Modal transparent visible={!!purchase} animationType="fade" onRequestClose={()=>setPurchase(null)}><View style={s.overlay}><View style={s.dialog}><Text style={s.dialogTitle}>상품을 구매하시겠습니까?</Text><View style={s.dialogButtons}><Pressable onPress={()=>setPurchase(null)} style={[s.dialogButton,s.cancel]}><Text style={s.buttonText}>취소</Text></Pressable><Pressable onPress={()=>setPurchase(null)} style={[s.dialogButton,s.buy]}><Text style={s.buttonText}>구매하기</Text></Pressable></View></View></View></Modal></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.white},content:{paddingHorizontal:14,paddingTop:16,paddingBottom:92},heading:{marginLeft:2,fontSize:20,fontWeight:'600',lineHeight:24,color:colors.black,marginBottom:16},chips:{gap:8,paddingRight:14},sort:{height:48,flexDirection:'row',alignItems:'center',justifyContent:'flex-end'},sortText:{fontSize:12,color:colors.g500},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.25)',alignItems:'center',justifyContent:'center',paddingHorizontal:16},dialog:{width:'100%',maxWidth:370,borderRadius:radius.lg,backgroundColor:colors.white,paddingHorizontal:20,paddingTop:40,paddingBottom:16,gap:32},dialogTitle:{textAlign:'center',fontSize:16,fontWeight:'500',color:colors.black},dialogButtons:{flexDirection:'row',gap:8},dialogButton:{flex:1,height:56,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},cancel:{backgroundColor:colors.g300},buy:{backgroundColor:colors.primary500},buttonText:{color:colors.white,fontSize:16,fontWeight:'600'}});
