import React,{useState} from 'react';
import { Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { AppHeader,BottomNavigation,Product,ProductCard,ReservationStatus } from '../components/home';
import { colors,radius } from '../theme';
import CloseIcon from '../../icon/x.svg';

export type ReservationItem={id:number;product:Product;status:ReservationStatus;quantity:number;reservedAt:string};
const reasons=['일정 및 픽업 시간 변경','상품/옵션을 잘못 선택함','단순 변심 및 다른 상품 구매','기타 (직접 입력)'];

export function ReservationHistoryScreen({items,onHome,onMap,onMyPage,onCancel,onDelete,onBuy}:{items:ReservationItem[];onHome:()=>void;onMap:()=>void;onMyPage:()=>void;onCancel:(id:number,reason:string)=>void;onDelete:(id:number)=>void;onBuy:(product:Product)=>void}){
 const[cancelId,setCancelId]=useState<number|null>(null);const[reason,setReason]=useState('');const[other,setOther]=useState('');const[rejected,setRejected]=useState<ReservationItem|null>(null);
 const submit=()=>{if(cancelId===null)return;const value=reason==='기타 (직접 입력)'?other.trim():reason;if(!value)return;onCancel(cancelId,value);setCancelId(null);setReason('');setOther('')};
 return <View style={s.root}><AppHeader/><ScrollView contentContainerStyle={s.content}><Text style={s.title}>나의 예약 내역</Text><Text style={s.description}>승인 전(대기중) 예약 취소 가능, 승인 후 예약 취소 불가능</Text>{items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>예약한 상품/자원이 없어요.</Text><Text style={s.emptyBody}>내 주변 할인 상품/자원들을 확인하고 예약을 진행해 보세요!</Text></View>:items.map(item=><ProductCard key={item.id} product={item.product} liked={false} onLike={()=>{}} onBuy={()=>onBuy(item.product)} onReserve={()=>{}} status={item.status} onCancel={()=>setCancelId(item.id)} onDelete={()=>onDelete(item.id)} onReason={()=>setRejected(item)}/>)}</ScrollView><BottomNavigation active="reservations" onSelect={tab=>tab==='home'?onHome():tab==='map'?onMap():tab==='mypage'?onMyPage():undefined}/><CancelModal visible={cancelId!==null} reason={reason} other={other} onReason={setReason} onOther={setOther} onClose={()=>setCancelId(null)} onConfirm={submit}/><ReasonModal item={rejected} onClose={()=>setRejected(null)}/></View>;
}
function CancelModal({visible,reason,other,onReason,onOther,onClose,onConfirm}:{visible:boolean;reason:string;other:string;onReason:(v:string)=>void;onOther:(v:string)=>void;onClose:()=>void;onConfirm:()=>void}){const valid=!!reason&&(reason!=='기타 (직접 입력)'||!!other.trim());return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><View style={s.dim}><Pressable style={StyleSheet.absoluteFill} onPress={onClose}/><View style={s.sheet}><View style={s.sheetHead}><Text style={s.sheetTitle}>예약 취소 사유를 알려주세요.</Text><Pressable onPress={onClose}><CloseIcon width={24} height={24} color={colors.black}/></Pressable></View>{reasons.map(x=><Pressable key={x} style={s.reason} onPress={()=>onReason(x)}><View style={[s.radio,reason===x&&s.radioOn]}>{reason===x?<View style={s.dot}/>:null}</View><Text style={s.reasonText}>{x}</Text></Pressable>)}{reason==='기타 (직접 입력)'?<View style={s.otherBox}><TextInput multiline maxLength={50} value={other} onChangeText={onOther} placeholder="취소 사유를 입력해 주세요." placeholderTextColor={colors.g400} style={s.otherInput}/><Text style={s.count}>{other.length}/50</Text></View>:null}<Pressable disabled={!valid} onPress={onConfirm} style={[s.confirm,!valid&&s.disabled]}><Text style={[s.confirmText,!valid&&s.disabledText]}>예약 취소</Text></Pressable></View></View></Modal>}
function ReasonModal({item,onClose}:{item:ReservationItem|null;onClose:()=>void}){return <Modal transparent visible={!!item} animationType="fade" onRequestClose={onClose}><View style={s.centerDim}><View style={s.dialog}><Text style={s.dialogTitle}>거절 사유</Text><Text style={s.rejectReason}>[당일 재고 소진]</Text><Pressable style={s.confirm} onPress={onClose}><Text style={s.confirmText}>확인</Text></Pressable></View></View></Modal>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.white},content:{paddingHorizontal:14,paddingTop:20,paddingBottom:92},title:{fontSize:20,fontWeight:'600',color:colors.black},description:{fontSize:12,color:colors.g500,marginTop:8,marginBottom:20},empty:{alignItems:'center',paddingTop:180,gap:8},emptyTitle:{fontSize:18,fontWeight:'600',color:colors.g800},emptyBody:{fontSize:14,color:colors.g500,textAlign:'center'},dim:{flex:1,backgroundColor:'rgba(17,17,17,.25)',justifyContent:'flex-end'},sheet:{backgroundColor:colors.white,borderTopLeftRadius:24,borderTopRightRadius:24,paddingHorizontal:16,paddingTop:22,paddingBottom:34},sheetHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},sheetTitle:{fontSize:18,fontWeight:'600',color:colors.black},reason:{height:48,flexDirection:'row',alignItems:'center',gap:10},radio:{width:22,height:22,borderRadius:11,borderWidth:2,borderColor:colors.g300,alignItems:'center',justifyContent:'center'},radioOn:{borderColor:colors.primary500},dot:{width:12,height:12,borderRadius:6,backgroundColor:colors.primary500},reasonText:{fontSize:15,color:colors.g800},otherBox:{height:96,borderWidth:1,borderColor:colors.g300,borderRadius:radius.sm,padding:12,marginTop:4,marginBottom:14},otherInput:{flex:1,fontSize:14,color:colors.black,textAlignVertical:'top',padding:0},count:{fontSize:11,color:colors.g400,textAlign:'right'},confirm:{height:56,borderRadius:radius.md,backgroundColor:colors.primary500,alignItems:'center',justifyContent:'center',marginTop:12},disabled:{backgroundColor:colors.g200},confirmText:{fontSize:16,fontWeight:'600',color:colors.white},disabledText:{color:colors.g400},centerDim:{flex:1,backgroundColor:'rgba(17,17,17,.25)',alignItems:'center',justifyContent:'center',paddingHorizontal:16},dialog:{width:'100%',maxWidth:370,borderRadius:radius.lg,backgroundColor:colors.white,padding:20},dialogTitle:{fontSize:18,fontWeight:'600',textAlign:'center',color:colors.black},rejectReason:{fontSize:16,textAlign:'center',color:colors.g800,paddingVertical:30}});
