import React from 'react';
import { Pressable,StyleSheet,Text,View } from 'react-native';
import { colors,radius } from '../theme';
import { Card,Tag } from './ui';
import BellIcon from '../../icon/bell.svg'; import HeartIcon from '../../icon/heart.svg'; import HomeIcon from '../../icon/home.svg'; import MapPinIcon from '../../icon/map_pin.svg'; import ReservationIcon from '../../icon/reservation.svg'; import LoaderIcon from '../../icon/loader.svg'; import UserIcon from '../../icon/user.svg';
import BrandLogo from '../../icon/로컬타임_로고1 1.svg';

export type Product={id:number;title:string;discount:string;shop:string;location:string;detail:string;insight:string;original:string;price:string;remaining:string;urgent?:boolean};
export type ReservationStatus='waiting'|'confirmed'|'rejected';

export function AppHeader(){return <View style={s.header}><View style={s.logo}><BrandLogo width="100%" height="100%" viewBox="140 190 1220 320"/></View><Pressable accessibilityRole="button" accessibilityLabel="알림" hitSlop={10}><BellIcon width={25} height={25} color={colors.black}/></Pressable></View>}

export function ProductCard({product,liked,onLike,onBuy,onReserve,status,onCancel,onDelete,onReason}:{product:Product;liked:boolean;onLike:()=>void;onBuy:()=>void;onReserve:()=>void;status?:ReservationStatus;onCancel?:()=>void;onDelete?:()=>void;onReason?:()=>void}){
 const state=status?{waiting:['대기중',colors.primary500,'rgba(243,171,36,.15)'],confirmed:['확정',colors.success,'rgba(102,219,90,.15)'],rejected:['거절',colors.danger,'rgba(235,64,49,.15)']}[status]:null;
 return <Card style={s.card}><View style={s.cardHead}><Pressable accessibilityRole="button" accessibilityLabel="찜하기" accessibilityState={{selected:liked}} onPress={onLike}><HeartIcon width={24} height={24} color={liked?colors.primary500:colors.g300} fill={liked?colors.primary500:'none'}/></Pressable>{state?<View style={s.stateRow}><Text style={s.stateLabel}>예약상태 |</Text><View style={[s.stateTag,{borderColor:state[1],backgroundColor:state[2]}]}><Text style={[s.stateText,{color:state[1]}]}>{state[0]}</Text></View></View>:null}</View>
 <View style={s.body}><View style={s.titleRow}><Text numberOfLines={1} style={s.title}>{product.title}</Text><Text style={s.discount}>{product.discount}</Text></View><View style={s.metaRow}><Text style={s.shop}>{product.shop}</Text><Text style={s.location}>{product.location}</Text></View><View style={s.metaRow}><Text style={s.detail}>{product.detail}</Text>{product.urgent?<Tag tone="info">마감임박</Tag>:null}</View><View style={s.insight}><LoaderIcon width={24} height={24} color={colors.primary500}/><Text style={s.insightText}>{product.insight}</Text></View><View style={s.priceRow}><Text style={s.original}>{product.original}</Text><Text style={s.price}>{product.price}</Text></View><Text style={s.remaining}>{product.remaining}</Text></View>
 {status==='waiting'?<OneButton label="예약 취소" onPress={onCancel} muted/>:status==='confirmed'?<OneButton label="구매하기" onPress={onBuy}/>:status==='rejected'?<View style={s.actions}><Action label="거절 사유 확인" onPress={onReason}/><Action label="삭제" onPress={onDelete} muted/></View>:<View style={s.actions}><Action label="즉시 구매" onPress={onBuy}/><Action label="예약하기" onPress={onReserve} muted/></View>}</Card>;
}
function Action({label,onPress,muted}:{label:string;onPress?:()=>void;muted?:boolean}){return <Pressable onPress={onPress} style={[s.action,muted?s.secondary:s.primary]}><Text style={s.buttonText}>{label}</Text></Pressable>}
function OneButton({label,onPress,muted}:{label:string;onPress?:()=>void;muted?:boolean}){return <Pressable onPress={onPress} style={[s.oneButton,muted?s.secondary:s.primary]}><Text style={s.buttonText}>{label}</Text></Pressable>}
const navItems=[{label:'홈',Icon:HomeIcon},{label:'지도',Icon:MapPinIcon},{label:'예약내역',Icon:ReservationIcon},{label:'마이페이지',Icon:UserIcon}];
export type HomeTab='home'|'reservations'|'mypage';
export function BottomNavigation({active='home',onSelect}:{active?:HomeTab;onSelect?:(tab:HomeTab)=>void}){return <View style={s.nav}>{navItems.map(({label,Icon},i)=>{const tab:HomeTab=i===2?'reservations':i===3?'mypage':'home';const selected=(active==='home'&&i===0)||(active==='reservations'&&i===2)||(active==='mypage'&&i===3);const color=selected?colors.primary500:colors.g400;return <Pressable key={label} onPress={()=>onSelect?.(tab)} style={s.navItem}><Icon width={24} height={24} color={color}/><Text style={[s.navLabel,{color}]}>{label}</Text></Pressable>})}</View>}
const s=StyleSheet.create({header:{height:56,borderBottomWidth:1,borderBottomColor:colors.g200,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{width:99,height:24},card:{paddingHorizontal:12,paddingVertical:16,marginBottom:8,gap:16},cardHead:{paddingBottom:16,borderBottomWidth:1,borderBottomColor:colors.g200,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},stateRow:{flexDirection:'row',alignItems:'center',gap:6},stateLabel:{fontSize:16,fontWeight:'600',color:colors.g300},stateTag:{paddingHorizontal:8,paddingVertical:6,borderRadius:8,borderWidth:2},stateText:{fontSize:14,fontWeight:'600'},body:{paddingBottom:16,borderBottomWidth:1,borderBottomColor:colors.g200,gap:6},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},title:{flex:1,fontSize:20,fontWeight:'600',color:colors.black},discount:{fontSize:16,fontWeight:'600',color:colors.info},metaRow:{flexDirection:'row',alignItems:'center',gap:8},shop:{fontSize:14,fontWeight:'600',color:colors.g800},location:{fontSize:12,color:colors.g600},detail:{fontSize:12,color:colors.g600},insight:{marginTop:2,minHeight:64,paddingHorizontal:8,paddingVertical:16,borderRadius:radius.sm,backgroundColor:'rgba(255,237,204,.5)',flexDirection:'row',alignItems:'center',gap:8},insightText:{flex:1,fontSize:12,fontWeight:'600',lineHeight:16,color:colors.primary500},priceRow:{marginTop:3,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},original:{fontSize:16,color:colors.g800,textDecorationLine:'line-through'},price:{fontSize:20,fontWeight:'600',color:colors.danger},remaining:{fontSize:12,color:colors.g600},actions:{flexDirection:'row',gap:16},action:{flex:1,height:56,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},oneButton:{height:56,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},primary:{backgroundColor:colors.primary500},secondary:{backgroundColor:colors.g300},buttonText:{color:colors.white,fontSize:16,lineHeight:24,fontWeight:'600'},nav:{position:'absolute',left:0,right:0,bottom:0,height:66,paddingHorizontal:12,backgroundColor:colors.white,flexDirection:'row',justifyContent:'space-between'},navItem:{flex:1,paddingVertical:8,alignItems:'center',gap:8},navLabel:{fontSize:12,fontWeight:'600'}});
