import React from 'react';
import { Image,Modal,Pressable,StyleSheet,Text,View } from 'react-native';
import { colors,radius } from '../theme';
import { Card,Tag } from './ui'; import { NotificationCenter } from './notifications';
import { DeviceFrame } from './DeviceFrame';
import { notificationApi } from '../api';
import BellIcon from '../../icon/bell.svg'; import HeartIcon from '../../icon/heart.svg'; import HomeIcon from '../../icon/home.svg'; import MapPinIcon from '../../icon/map_pin.svg'; import PaymentIcon from '../../icon/reservation.svg'; import LoaderIcon from '../../icon/loader.svg'; import UserIcon from '../../icon/user.svg';
import BrandLogo from '../../icon/로컬타임_로고1 1.svg';

export type Product={id:number;title:string;discount:string;shop:string;location:string;detail:string;insight:string;original:string;price:string;remaining:string;imageUrls?:string[];urgent?:boolean;deadlineAt?:number;distanceMeters?:number;discountRate?:number;lat?:number|null;lng?:number|null};
export type PaymentDisplayStatus='pending'|'accepted'|'refunded';

export function AppHeader({role='buyer'}:{role?:'buyer'|'seller'}){const[open,setOpen]=React.useState(false);const[hasUnread,setHasUnread]=React.useState(false);const refresh=React.useCallback(()=>notificationApi.list({filter:'UNREAD',size:1}).then(page=>setHasUnread(page.content.length>0)).catch(()=>setHasUnread(false)),[]);React.useEffect(()=>{void refresh()},[refresh]);const close=()=>{setOpen(false);void refresh()};return <><View style={s.header}><View style={s.logo}><BrandLogo width="100%" height="100%" viewBox="140 190 1220 320"/></View><Pressable accessibilityRole="button" accessibilityLabel="알림" hitSlop={10} onPress={()=>setOpen(true)}><BellIcon width={25} height={25} color={colors.black}/>{hasUnread?<View style={{position:'absolute',right:-1,top:-1,width:7,height:7,borderRadius:4,backgroundColor:colors.danger,borderWidth:1,borderColor:colors.white}}/>:null}</Pressable></View><Modal visible={open} animationType="fade" onRequestClose={close}><DeviceFrame><NotificationCenter role={role} onBack={close}/></DeviceFrame></Modal></>}

export function ProductCard({product,liked,onLike,onBuy,status,onDelete,onReason,purchaseQuantity,totalAmount}:{product:Product;liked:boolean;onLike:()=>void;onBuy:()=>void;status?:PaymentDisplayStatus;onDelete?:()=>void;onReason?:()=>void;purchaseQuantity?:number;totalAmount?:number}){
 const state=status?{pending:['판매자 확인 대기',colors.primary500,'rgba(243,171,36,.15)'],accepted:['판매 수락',colors.success,'rgba(102,219,90,.15)'],refunded:['환불 완료',colors.danger,'rgba(235,64,49,.15)']}[status]:null;
 if(!status)return <Pressable onPress={onBuy} style={compact.productCard}><View style={compact.productImageWrap}>{product.imageUrls?.[0]?<Image source={{uri:product.imageUrls[0]}} resizeMode="cover" style={compact.productImage}/>:<View style={compact.imageFallback}/>} {product.urgent?<View style={compact.urgent}><Text style={compact.urgentText}>마감임박</Text></View>:null}<Pressable accessibilityLabel="찜하기" onPress={event=>{event.stopPropagation();onLike()}} style={compact.heartCircle}><HeartIcon width={22} height={22} color={liked?colors.primary500:colors.white} fill={liked?colors.primary500:colors.white}/></Pressable></View><View style={compact.productContents}><Text numberOfLines={1} style={compact.productTitle}>{product.title}</Text><View style={compact.storeRow}><MapPinIcon width={14} height={14} color={colors.g500}/><Text numberOfLines={1} style={compact.productShop}>{product.shop}</Text></View><Text style={compact.productPrice}>{product.price}</Text></View></Pressable>;
 return <Card style={s.card}><View style={s.cardHead}><Pressable accessibilityRole="button" accessibilityLabel="찜하기" accessibilityState={{selected:liked}} onPress={onLike}><HeartIcon width={24} height={24} color={liked?colors.primary500:colors.g300} fill={liked?colors.primary500:'none'}/></Pressable>{state?<View style={s.stateRow}><Text style={s.stateLabel}>결제상태 |</Text><View style={[s.stateTag,{borderColor:state[1],backgroundColor:state[2]}]}><Text style={[s.stateText,{color:state[1]}]}>{state[0]}</Text></View></View>:null}</View>
 <View style={s.body}><View style={s.titleRow}><Text numberOfLines={1} style={s.title}>{product.title}</Text><Text style={s.discount}>{product.discount}</Text></View><View style={s.metaRow}><Text style={s.shop}>{product.shop}</Text><Text style={s.location}>{product.location}</Text></View><View style={s.metaRow}><Text style={s.detail}>{product.detail}</Text>{product.urgent?<Tag tone="info">마감임박</Tag>:null}</View>{!status?<View style={s.insight}><LoaderIcon width={24} height={24} color={colors.primary500}/><Text style={s.insightText}>{product.insight}</Text></View>:null}<View style={s.priceRow}><Text style={s.original}>{product.original}</Text><Text style={s.price}>{product.price}</Text></View><Text style={s.remaining}>{product.remaining}</Text>{status?<View style={s.purchaseSummary}><View><Text style={s.purchaseLabel}>구매 수량</Text><Text style={s.purchaseValue}>{purchaseQuantity}개</Text></View><View style={s.purchaseDivider}/><View style={s.purchaseTotal}><Text style={s.purchaseLabel}>총 결제 금액</Text><Text style={s.purchaseTotalValue}>{totalAmount?.toLocaleString()}원</Text></View></View>:null}</View>
 {status==='refunded'?<View style={s.actions}><Action label="환불 사유 확인" onPress={onReason}/><Action label="삭제" onPress={onDelete} muted/></View>:status==='accepted'?<OneButton label="내역 삭제" onPress={onDelete} muted/>:status?null:<OneButton label="구매하기" onPress={onBuy}/>}</Card>;
}
function Action({label,onPress,muted}:{label:string;onPress?:()=>void;muted?:boolean}){return <Pressable onPress={onPress} style={[s.action,muted?s.secondary:s.primary]}><Text style={s.buttonText}>{label}</Text></Pressable>}
function OneButton({label,onPress,muted}:{label:string;onPress?:()=>void;muted?:boolean}){return <Pressable onPress={onPress} style={[s.oneButton,muted?s.secondary:s.primary]}><Text style={s.buttonText}>{label}</Text></Pressable>}
const compact=StyleSheet.create({productCard:{width:'48.4%',borderWidth:1,borderColor:colors.g200,borderRadius:16,overflow:'hidden',backgroundColor:colors.white},productImageWrap:{height:215,position:'relative',backgroundColor:colors.g100},productImage:{width:'100%',height:'100%'},imageFallback:{flex:1,backgroundColor:colors.g100},urgent:{position:'absolute',left:10,top:10,paddingHorizontal:4,paddingVertical:2,borderRadius:4,backgroundColor:colors.primary500},urgentText:{fontSize:12,fontWeight:'600',color:colors.white},heartCircle:{position:'absolute',right:10,top:10,width:40,height:40,borderRadius:20,backgroundColor:'rgba(255,255,255,.65)',alignItems:'center',justifyContent:'center'},productContents:{paddingHorizontal:8,paddingTop:12,paddingBottom:12,gap:6},productTitle:{fontSize:14,fontWeight:'600',color:colors.black},storeRow:{flexDirection:'row',alignItems:'center',gap:2},productShop:{flex:1,fontSize:10,color:colors.g600},productPrice:{marginTop:4,fontSize:16,fontWeight:'600',color:colors.info}});
const navItems=[{label:'홈',Icon:HomeIcon},{label:'지도',Icon:MapPinIcon},{label:'결제내역',Icon:PaymentIcon},{label:'마이페이지',Icon:UserIcon}];
export type HomeTab='home'|'map'|'purchases'|'mypage';
export function BottomNavigation({active='home',onSelect}:{active?:HomeTab;onSelect?:(tab:HomeTab)=>void}){return <View style={s.nav}>{navItems.map(({label,Icon},i)=>{const tab:HomeTab=i===1?'map':i===2?'purchases':i===3?'mypage':'home';const selected=active===tab;const color=selected?colors.primary500:colors.g400;return <Pressable key={label} onPress={()=>onSelect?.(tab)} style={s.navItem}><Icon width={24} height={24} color={color}/><Text style={[s.navLabel,{color}]}>{label}</Text></Pressable>})}</View>}
const s=StyleSheet.create({header:{height:56,borderBottomWidth:1,borderBottomColor:colors.g200,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{width:99,height:24},card:{paddingHorizontal:12,paddingVertical:16,marginBottom:8,gap:16},cardHead:{paddingBottom:16,borderBottomWidth:1,borderBottomColor:colors.g200,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},stateRow:{flexDirection:'row',alignItems:'center',gap:6},stateLabel:{fontSize:16,fontWeight:'600',color:colors.g300},stateTag:{paddingHorizontal:8,paddingVertical:6,borderRadius:8,borderWidth:2},stateText:{fontSize:14,fontWeight:'600'},body:{paddingBottom:16,borderBottomWidth:1,borderBottomColor:colors.g200,gap:6},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},title:{flex:1,fontSize:20,fontWeight:'600',color:colors.black},discount:{fontSize:16,fontWeight:'600',color:colors.info},metaRow:{flexDirection:'row',alignItems:'center',gap:8},shop:{fontSize:14,fontWeight:'600',color:colors.g800},location:{fontSize:12,color:colors.g600},detail:{fontSize:12,color:colors.g600},insight:{marginTop:2,minHeight:64,paddingHorizontal:8,paddingVertical:16,borderRadius:radius.sm,backgroundColor:'rgba(255,237,204,.5)',flexDirection:'row',alignItems:'center',gap:8},insightText:{flex:1,fontSize:12,fontWeight:'600',lineHeight:16,color:colors.primary500},priceRow:{marginTop:3,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},original:{fontSize:16,color:colors.g800,textDecorationLine:'line-through'},price:{fontSize:20,fontWeight:'600',color:colors.danger},remaining:{fontSize:12,color:colors.g600},purchaseSummary:{marginTop:12,paddingTop:14,borderTopWidth:1,borderTopColor:colors.g200,flexDirection:'row',alignItems:'center'},purchaseLabel:{fontSize:12,color:colors.g500},purchaseValue:{marginTop:4,fontSize:15,fontWeight:'600',color:colors.g800},purchaseDivider:{width:1,height:36,marginHorizontal:18,backgroundColor:colors.g200},purchaseTotal:{flex:1,alignItems:'flex-end'},purchaseTotalValue:{marginTop:4,fontSize:17,fontWeight:'700',color:colors.black},actions:{flexDirection:'row',gap:16},action:{flex:1,height:56,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},oneButton:{height:56,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},primary:{backgroundColor:colors.primary500},secondary:{backgroundColor:colors.g300},buttonText:{color:colors.white,fontSize:16,lineHeight:24,fontWeight:'600'},nav:{position:'absolute',left:0,right:0,bottom:0,height:66,paddingHorizontal:12,backgroundColor:colors.white,flexDirection:'row',justifyContent:'space-between'},navItem:{flex:1,paddingVertical:8,alignItems:'center',gap:8},navLabel:{fontSize:12,fontWeight:'600'}});
