import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme';
import ChevronLeft from '../../icon/chevron_left.svg';
import PaymentIcon from '../../icon/reservation.svg';
import ShoppingIcon from '../../icon/shopping-bag.svg';
import LoaderIcon from '../../icon/loader.svg';
import { notificationApi } from '../api';
import { mockBuyerNotices, mockSellerNotices } from '../mocks/data';
type Role='buyer'|'seller'; type Notice={id:number;title:string;body:string;date:string;unread:boolean;kind:'payment'|'product'|'ai'|'system'};
export function NotificationCenter({role,onBack}:{role:Role;onBack:()=>void}){const[tab,setTab]=useState<'news'|'unread'>('news');const[items,setItems]=useState<Notice[]>(role==='seller'?mockSellerNotices:mockBuyerNotices);useEffect(()=>{notificationApi.list({filter:'ALL',size:50}).then(page=>setItems(page.content.map(item=>({id:item.id,title:item.title,body:item.message,date:new Date(item.createdAt).toLocaleString('ko-KR'),unread:!item.read,kind:item.referenceType==='PAYMENT'?'payment':item.referenceType==='PRODUCT'?'product':item.type.includes('AI')?'ai':'system'})))).catch(()=>undefined)},[role]);const shown=useMemo(()=>tab==='unread'?items.filter(item=>item.unread):items,[items,tab]);return <View style={s.root}><View style={s.header}><Pressable onPress={onBack}><ChevronLeft width={24} height={24} color={colors.black}/></Pressable><Text style={s.headerTitle}>알림</Text><View style={{width:24}}/></View><View style={s.tabs}><Pressable style={[s.tab,tab==='news'&&s.tabOn]} onPress={()=>setTab('news')}><Text style={s.tabText}>새 소식</Text></Pressable><Pressable style={[s.tab,tab==='unread'&&s.tabOn]} onPress={()=>setTab('unread')}><Text style={s.tabText}>미확인</Text></Pressable></View><ScrollView showsVerticalScrollIndicator={false}>{shown.map(item=><Pressable key={item.id} style={[s.notice,item.unread&&s.unread]} onPress={()=>{setItems(list=>list.map(value=>value.id===item.id?{...value,unread:false}:value));void notificationApi.read(item.id).catch(()=>undefined)}}><View style={s.iconCircle}><NoticeIcon kind={item.kind}/></View><View style={s.copy}><Text numberOfLines={1} style={s.title}>{item.title}</Text><Text numberOfLines={1} style={s.body}>{item.body}</Text><Text style={s.date}>{item.date}</Text></View></Pressable>)}{shown.length===0?<View style={s.empty}><Text style={s.emptyTitle}>미확인 알림이 없습니다.</Text><Text style={s.emptyBody}>새로운 알림이 오면 이곳에서 확인할 수 있어요.</Text></View>:null}</ScrollView></View>}
function NoticeIcon({kind}:{kind:Notice['kind']}){if(kind==='payment')return <PaymentIcon width={24} height={24} color={colors.black}/>;if(kind==='product')return <ShoppingIcon width={24} height={24} color={colors.black}/>;if(kind==='ai')return <LoaderIcon width={24} height={24} color={colors.black}/>;return <Text style={s.systemIcon}>!</Text>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.white},header:{height:56,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{fontSize:16,fontWeight:'600'},tabs:{height:44,flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabOn:{borderBottomWidth:2,borderBottomColor:colors.black},tabText:{fontSize:16,fontWeight:'500'},notice:{height:100,paddingHorizontal:16,paddingVertical:20,flexDirection:'row',gap:12},unread:{backgroundColor:'rgba(255,237,204,.5)'},iconCircle:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:colors.g200,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},copy:{flex:1,gap:5},title:{fontSize:16,fontWeight:'600'},body:{fontSize:12,color:colors.g600},date:{fontSize:10,color:colors.g400},systemIcon:{fontSize:20,fontWeight:'600'},empty:{paddingTop:180,alignItems:'center',gap:8},emptyTitle:{fontSize:16,fontWeight:'600'},emptyBody:{fontSize:12,color:colors.g500}});
