import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme';
import ChevronLeft from '../../icon/chevron_left.svg';
import ReservationIcon from '../../icon/reservation.svg';
import ShoppingIcon from '../../icon/shopping-bag.svg';
import LoaderIcon from '../../icon/loader.svg';
type Role='buyer'|'seller'; type Notice={id:number;title:string;body:string;date:string;unread:boolean;kind:'reservation'|'product'|'ai'|'system'};
const sellerSeed:Notice[]=[{id:1,title:'새로운 예약 요청이 들어왔습니다!',body:'[흑돼지 도시락] 상품 2개 예약 요청이 있습니다. 마감 전 빠른 승인이 필요해요.',date:'2026.07.11 · 오후 6:15',unread:true,kind:'reservation'},{id:2,title:'AI 실시간 할인가 변동 제안',body:'매장 주변 유동인구가 급증했습니다. 추천 할인가를 확인해 보세요.',date:'2026.07.11 · 오후 6:02',unread:false,kind:'ai'},{id:3,title:'[공지] 로컬타임 시스템 정기 점검 안내',body:'목요일 새벽 2시부터 4시까지 시스템을 점검합니다.',date:'2026.07.09 · 오후 8:12',unread:true,kind:'system'}];
const buyerSeed:Notice[]=[{id:1,title:'예약이 승인되었습니다.',body:'[춘자네 귀한 협재점] 당일 공실 예약이 승인되었습니다.',date:'2026.07.11 · 오후 5:40',unread:true,kind:'product'},{id:2,title:'예약이 취소되었습니다.',body:'매장 재고 소진으로 인해 예약이 거절되었습니다.',date:'2026.07.10 · 오후 8:12',unread:false,kind:'product'},{id:3,title:'찜 상품 마감임박!',body:'찜 목록 상품의 판매 시간이 얼마 남지 않았어요.',date:'2026.07.10 · 오후 9:30',unread:false,kind:'product'},{id:4,title:'[공지] 로컬타임 시스템 정기 점검 안내',body:'목요일 새벽 2시부터 4시까지 시스템을 점검합니다.',date:'2026.07.09 · 오후 8:12',unread:true,kind:'system'}];
export function NotificationCenter({role,onBack}:{role:Role;onBack:()=>void}){const[tab,setTab]=useState<'news'|'unread'>('news');const[items,setItems]=useState(role==='seller'?sellerSeed:buyerSeed);const shown=useMemo(()=>tab==='unread'?items.filter(item=>item.unread):items,[items,tab]);return <View style={s.root}><View style={s.header}><Pressable onPress={onBack}><ChevronLeft width={24} height={24} color={colors.black}/></Pressable><Text style={s.headerTitle}>알림</Text><View style={{width:24}}/></View><View style={s.tabs}><Pressable style={[s.tab,tab==='news'&&s.tabOn]} onPress={()=>setTab('news')}><Text style={s.tabText}>새 소식</Text></Pressable><Pressable style={[s.tab,tab==='unread'&&s.tabOn]} onPress={()=>setTab('unread')}><Text style={s.tabText}>미확인</Text></Pressable></View><ScrollView>{shown.map(item=><Pressable key={item.id} style={[s.notice,item.unread&&s.unread]} onPress={()=>setItems(list=>list.map(value=>value.id===item.id?{...value,unread:false}:value))}><View style={s.iconCircle}><NoticeIcon kind={item.kind}/></View><View style={s.copy}><Text numberOfLines={1} style={s.title}>{item.title}</Text><Text numberOfLines={1} style={s.body}>{item.body}</Text><Text style={s.date}>{item.date}</Text></View></Pressable>)}{shown.length===0?<View style={s.empty}><Text style={s.emptyTitle}>미확인 알림이 없습니다.</Text><Text style={s.emptyBody}>새로운 알림이 오면 이곳에서 확인할 수 있어요.</Text></View>:null}</ScrollView></View>}
function NoticeIcon({kind}:{kind:Notice['kind']}){if(kind==='reservation')return <ReservationIcon width={24} height={24} color={colors.black}/>;if(kind==='product')return <ShoppingIcon width={24} height={24} color={colors.black}/>;if(kind==='ai')return <LoaderIcon width={24} height={24} color={colors.black}/>;return <Text style={s.systemIcon}>!</Text>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.white},header:{height:56,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{fontSize:16,fontWeight:'600'},tabs:{height:44,flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabOn:{borderBottomWidth:2,borderBottomColor:colors.black},tabText:{fontSize:16,fontWeight:'500'},notice:{height:100,paddingHorizontal:16,paddingVertical:20,flexDirection:'row',gap:12},unread:{backgroundColor:'rgba(255,237,204,.5)'},iconCircle:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:colors.g200,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},copy:{flex:1,gap:5},title:{fontSize:16,fontWeight:'600'},body:{fontSize:12,color:colors.g600},date:{fontSize:10,color:colors.g400},systemIcon:{fontSize:20,fontWeight:'600'},empty:{paddingTop:180,alignItems:'center',gap:8},emptyTitle:{fontSize:16,fontWeight:'600'},emptyBody:{fontSize:12,color:colors.g500}});
