import React, { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, TextInput, TextInputProps, View, ViewStyle } from 'react-native';
import { colors, radius } from '../theme';

export function ActionButton({children,onPress,disabled=false,dark=false}:{children:React.ReactNode;onPress?:()=>void;disabled?:boolean;dark?:boolean}) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[s.action,dark&&s.dark,disabled&&s.disabled,pressed&&!disabled&&s.pressed]}><Text style={[s.actionText,disabled&&s.disabledText]}>{children}</Text></Pressable>; }
export function Checkbox({checked,onPress}:{checked:boolean;onPress:()=>void}) { return <Pressable accessibilityRole="checkbox" accessibilityState={{checked}} onPress={onPress} style={[s.check,checked&&s.checkOn]}><Text style={s.checkMark}>{checked?'✓':''}</Text></Pressable>; }
export function Toggle({value,onChange}:{value:boolean;onChange:(v:boolean)=>void}) { return <Pressable accessibilityRole="switch" accessibilityState={{checked:value}} onPress={()=>onChange(!value)} style={[s.toggle,value&&s.toggleOn]}><View style={[s.handle,value&&s.handleOn]}/></Pressable>; }
export function Chip({selected,children,onPress}:{selected?:boolean;children:React.ReactNode;onPress?:()=>void}) { return <Pressable onPress={onPress} style={[s.chip,selected&&s.chipOn]}><Text style={[s.chipText,selected&&s.chipTextOn]}>{children}</Text></Pressable>; }
export function Tag({children,tone='primary'}:PropsWithChildren<{tone?:'primary'|'success'|'danger'}>) { return <View style={[s.tag,tone==='success'&&s.success,tone==='danger'&&s.danger]}><Text style={[s.tagText,tone==='success'&&s.successText,tone==='danger'&&s.dangerText]}>{children}</Text></View>; }
export function Field({label,error,...props}:TextInputProps&{label:string;error?:string}) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor={colors.g400} style={[s.input,!!error&&s.inputError]} {...props}/>{error?<Text style={s.error}>{error}</Text>:null}</View>; }
export function Radio({selected,label,onPress}:{selected:boolean;label?:string;onPress?:()=>void}) { return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={onPress} style={s.radioRow}><View style={[s.radio,selected&&s.radioOn]}>{selected?<View style={s.radioDot}/>:null}</View>{label?<Text style={s.radioLabel}>{label}</Text>:null}</Pressable>; }
export function Card({children,style}:PropsWithChildren<{style?:ViewStyle}>) { return <View style={[s.card,style]}>{children}</View>; }

const s=StyleSheet.create({action:{height:56,borderRadius:radius.md,backgroundColor:colors.primary500,alignItems:'center',justifyContent:'center',paddingHorizontal:16},dark:{backgroundColor:colors.g300},pressed:{backgroundColor:colors.primary700},disabled:{backgroundColor:colors.g200},actionText:{color:colors.white,fontSize:16,fontWeight:'600'},disabledText:{color:colors.g400},check:{width:24,height:24,borderWidth:2,borderColor:colors.g300,borderRadius:8,alignItems:'center',justifyContent:'center'},checkOn:{backgroundColor:colors.primary500,borderColor:colors.primary500},checkMark:{color:colors.white,fontWeight:'700'},toggle:{width:52,height:28,padding:2,borderRadius:14,backgroundColor:colors.g300},toggleOn:{backgroundColor:colors.primary500},handle:{width:24,height:24,borderRadius:12,backgroundColor:colors.white},handleOn:{transform:[{translateX:24}]},chip:{minWidth:52,height:40,paddingHorizontal:12,borderWidth:2,borderColor:colors.g300,borderRadius:20,alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:colors.primary500,borderColor:colors.primary500},chipText:{color:colors.g300,fontSize:16},chipTextOn:{color:colors.white,fontWeight:'600'},tag:{paddingHorizontal:8,paddingVertical:6,borderWidth:2,borderColor:colors.primary500,borderRadius:8,backgroundColor:'#fff8eb'},tagText:{color:colors.primary500,fontSize:14,fontWeight:'600'},success:{borderColor:colors.success,backgroundColor:'#e8f8ef'},successText:{color:colors.success},danger:{borderColor:colors.danger,backgroundColor:'#fff0f0'},dangerText:{color:colors.danger},field:{gap:6},label:{fontSize:14,fontWeight:'600',color:colors.g800},input:{height:52,paddingHorizontal:16,borderWidth:1,borderColor:colors.g300,borderRadius:radius.md,fontSize:16,color:colors.black},inputError:{borderColor:colors.danger},error:{fontSize:12,color:colors.danger},radioRow:{flexDirection:'row',alignItems:'center',gap:8},radio:{width:24,height:24,borderWidth:2,borderColor:colors.g300,borderRadius:12,alignItems:'center',justifyContent:'center'},radioOn:{borderColor:colors.primary500},radioDot:{width:12,height:12,borderRadius:6,backgroundColor:colors.primary500},radioLabel:{fontSize:16,color:colors.g800},card:{padding:16,borderWidth:1,borderColor:colors.g200,borderRadius:radius.md,backgroundColor:colors.white}});
